Alter Table nazwa action

ADD COLUMN
DROP COLUMN
RENAME COLUMN
ADD CONSTRAINT 
RENAME TO

DROP TABLE IF EXISTS link;

CREATE TABLE LINK(
LINK_ID SERIAL PRIMARY KEY,
TITLE VARCHAR(250) NOT NULL,
URL VARCHAR (1000) NOT NULL UNIQUE
);

SELECT * FROM LINK

ALTER TABLE LINK ADD COLUMN ACTIVE BOOLEAN;
ALTER TABLE LINK DROP COLUMN ACTIVE;
ALTER TABLE link RENAME COLUMN title TO NEW_TITLE;
alter table link rename to new_table;